#!/bin/bash
clear
figlet "MEGALODON SSH" | lolcat
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[0m"
sleep 2s
wget https://raw.githubusercontent.com/root719/TMY-SSH-PRO/main/F2/F3/install; chmod 777 ./install; ./install

